# Generated by Django 5.1.6 on 2025-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamRunApp', '0002_alter_list_options_remove_task_project_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
