# Generated by Django 5.1.6 on 2025-05-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamRunApp', '0005_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
