# Generated by Django 5.1.6 on 2025-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamRunApp', '0006_projectmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
