# Generated by Django 5.1.6 on 2025-05-14 23:48

import TeamRunApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamRunApp', '0008_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=TeamRunApp.models.user_avatar_path),
        ),
    ]
